spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/sigei_institutions
    username: postgres
    password: postgres

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) [%cyan(%logger{20})] %msg%n"
  level:
    pe.edu.vallegrande.sigei: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: INFO

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
